# Generated by Django 4.2.26 on 2025-12-22 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bboard', '0010_migration_1_add_rating'), ('bboard', '0011_migration_2_add_featured'), ('bboard', '0012_migration_3_add_views')]

    dependencies = [
        ('bboard', '0009_add_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Рейтинг не может быть отрицательным'), django.core.validators.MaxValueValidator(5.0, message='Рейтинг не может превышать 5.0')], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
