# Generated by Django 4.2.26 on 2025-12-22 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_add_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Рейтинг не может быть отрицательным'), django.core.validators.MaxValueValidator(5.0, message='Рейтинг не может превышать 5.0')], verbose_name='Рейтинг'),
        ),
    ]
